lokafy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('review.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

review/urls.py
from . import views
from django.urls import path
from django.contrib import admin

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

review/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='images', blank=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

review/views.py
from django.views import generic
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 4

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

review/templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <title>Lokafy</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css?family=Nunito+Sans&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>
    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .bg-light {
        background-color: #f7f7f7 !important;
        }
    </style>

        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <a class="navbar-brand" href="{% url 'home' %}"><img src="https://lokafy.com/static/images/logos/logo-blue.png?fffbaf6f6903" style="width=50px;height: 50px;" /></a>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black" href="#">Book a Tour</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black" href="#">PRICING</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black" href="#">REVIEWS</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black" href="#">FAQS</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black" href="#">ABOUT</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black" href="#">SIGN UP</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black" href="#">LOG IN</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock content %}
    </body>
</html>

review/templates/index.html
{% extends "base.html" %}
{% block content %}

<style>
*{
margin:0px;
padding:0px;
box-sizing:border-box;
}
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
    h1{
        text-align:center;
        }
    h1, header, footer, .container {
        margin-top: 64px;
     }
    .col-md-8 {
        margin-left: 15%;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>REVIEWS</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row " style="margin:5px;">
        <div class="d-flex justify-content-center flex-wrap">
            {% for post in post_list %}
            <div class="card col-6" ">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <img src="media/{{ post.image }}" style="width: 100%; height: auto;">
                    <h4 class="author" class="card-text text-muted h6" style="font-weight: bold; color: rgba(52, 219, 235); font-family:'Nunito Sans';">{{ post.author }}</h4>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}">+ Read More</a>
                </div>
            </div>

{% endfor %}

{% if is_paginated %}
    <nav aria-label="Page navigation conatiner"></nav>
        <ul class="pagination justify-content-center">
{% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
{% endif %}
{% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
{% endif %}
        </ul>
  </nav>
</div>

{% endif %}
{%endblock%}

review/templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <img src="../media/{{ post.image }}" style="width: 100%; height: auto;">
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}

review/templates/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">More reviews</h5>
    <div class="card-body">
        <img class="card-img-top" src="https://lokafy.s3.amazonaws.com/citypicture/44_helsinki-3778356_citypicture.jpg.384x160_q85_box-0%2C0%2C3500%2C1966_crop-scale_detail_upscale.jpg" alt="Card image cap">
        <a href="{% url 'post_detail' post.slug  %}">from Helsinki</a>
    </div>
    <div class="card-body">
        <img class="card-img-top" src="https://lokafy.s3.amazonaws.com/citypicture/38_citypicture.jpg.384x160_q85_box-0%2C284%2C5317%2C3279_crop-scale_detail_upscale.jpg" alt="Card image cap">
        <a href="">from Helsinki</a>
    </div>
    <div class="card-body">
        <img class="card-img-top" src="https://lokafy.s3.amazonaws.com/userreview/938/bff121c8ca6f462b9606a7997d030bff_userpicturebff121c8ca6f462b9606a7997d030bff.384x16_q85_box-0%2C0%2C3264%2C2448_crop-scale_detail_upscale.jpg" alt="Card image cap">
        <a href="">from Helsinki</a>
    </div>
    <div class="card-body">
        <img class="card-img-top" src="https://lokafy.s3.amazonaws.com/citypicture/71_citypicture.jpg.384x160_q85_box-0%2C977%2C2304%2C2275_crop-scale_detail_upscale.jpg" alt="Card image cap">
        <a href="">from Helsinki</a>
    </div>
</div>
</div>

{% endblock sidebar %}